import os
import time
import requests
from pytrends.request import TrendReq
from gradio_client import Client
from gtts import gTTS
from moviepy.editor import VideoFileClip, AudioFileClip
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google_auth_oauthlib.flow import InstalledAppFlow
from google.oauth2.credentials import Credentials

# --- 1. TREND TESPİTİ ---
def get_trending_topic():
    print("[1/5] Trendler analiz ediliyor...")
    try:
        pytrends = TrendReq(hl='en-US', tz=360)
        trending = pytrends.trending_searches(pn='united_states')
        topic = str(trending.iloc[0][0])
        print(f"Tespit Edilen Trend Topic: {topic}")
        return topic
    except Exception as e:
        print(f"Trend çekilemedi, varsayılan konu kullanılıyor: {e}")
        return "Futuristic AI City"

# --- 2. SIFIRDAN AI VİDEO ÜRETİMİ (%100 Bedava HuggingFace ZeroGPU) ---
def generate_100pct_ai_video(prompt):
    print("[2/5] %100 AI Video sıfırdan üretiliyor (ZeroGPU)...")
    try:
        client = Client("damo-vilab/ModelScopeT2V")
        result = client.predict(
            prompt,
            api_name="/predict"
        )
        print(f"AI Video başarıyla oluşturuldu: {result}")
        return result
    except Exception as e:
        print(f"AI Video üretimi sırasında hata: {e}")
        return None

# --- 3. SES VE VİDEO BİRLEŞTİRME (gTTS Düzeltildi) ---
def process_media(video_path, text_prompt):
    print("[3/5] Yapay zeka sesi oluşturuluyor ve birleştiriliyor...")
    audio_file = "voice.mp3"
    output_filename = "final_shorts.mp4"
    
    # gTTS kullanımı doğru kütüphane adıyla çağrılıyor
    tts = gTTS(text=f"Check out this viral trend: {text_prompt}", lang='en', slow=False)
    tts.save(audio_file)
    
    video_clip = VideoFileClip(video_path)
    audio_clip = AudioFileClip(audio_file)
    
    # Ses süresine göre videoyu döngüye al veya kırp
    if video_clip.duration < audio_clip.duration:
        final_clip = video_clip.loop(duration=audio_clip.duration).set_audio(audio_clip)
    else:
        final_clip = video_clip.set_duration(audio_clip.duration).set_audio(audio_clip)
        
    final_clip.write_videofile(
        output_filename, 
        codec='libx264', 
        audio_codec='aac',
        temp_audiofile='temp-audio.m4a',
        remove_temp=True
    )
    
    video_clip.close()
    audio_clip.close()
    return output_filename

# --- 4. YOUTUBE YÜKLEME, LİKE VE YORUM SABİTLEME ---
SCOPES = [
    'https://www.googleapis.com/auth/youtube.upload', 
    'https://www.googleapis.com/auth/youtube.force-ssl'
]

def get_youtube_client():
    creds = None
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    if not creds or not creds.valid:
        # Mevcut OAuth2 istemci dosyanız client_secret.json adıyla dizinde olmalıdır
        flow = InstalledAppFlow.from_client_secrets_file('client_secret.json', SCOPES)
        creds = flow.run_local_server(port=0)
        with open('token.json', 'w') as token:
            token.write(creds.to_json())
    return build('youtube', 'v3', credentials=creds)

def upload_and_interact(video_file, topic):
    print("[4/5] YouTube Shorts yükleniyor...")
    youtube = get_youtube_client()
    
    body = {
        'snippet': {
            'title': f"{topic} #Shorts #AI #Trending",
            'description': f"100% AI Generated video about {topic}.",
            'tags': [topic, 'Shorts', 'AI'],
            'categoryId': '28'
        },
        'status': {
            'privacyStatus': 'public',
            'selfDeclaredMadeForKids': False
        }
    }
    
    media = MediaFileUpload(video_file, chunksize=-1, resumable=True)
    request = youtube.videos().insert(part=','.join(body.keys()), body=body, media_body=media)
    response = request.execute()
    video_id = response['id']
    print(f"Video Başarıyla Yüklendi! Video ID: {video_id}")
    
    print("[5/5] Otomatik Beğeni ve Yorum Yapılıyor...")
    
    # 1. Beğeni Atma
    try:
        youtube.videos().rate(id=video_id, rating='like').execute()
        print("Otomatik LIKE atıldı.")
    except Exception as e:
        print(f"Beğeni hatası: {e}")
        
    # 2. Otomatik Yorum Ekleme
    try:
        youtube.commentThreads().insert(
            part="snippet",
            body={
                "snippet": {
                    "videoId": video_id,
                    "topLevelComment": {
                        "snippet": {
                            "textOriginal": "This video was 100% generated by AI! What do you think? 👇"
                        }
                    }
                }
            }
        ).execute()
        print("Otomatik yorum eklendi.")
    except Exception as e:
        print(f"Yorum hatası: {e}")

# --- AKIŞ BAŞLATICI ---
if __name__ == "__main__":
    trend = get_trending_topic()
    prompt_text = f"cinematic footage of {trend}, high quality, 8k render, trending on artstation"
    
    generated_video = generate_100pct_ai_video(prompt_text)
    
    if generated_video:
        final_file = process_media(generated_video, trend)
        upload_and_interact(final_file, trend)
    else:
        print("AI Video üretilemedi, işlem durduruldu.")
