name: YouTube Otomatik Yukleme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repodaki kodları çek
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Sistem Bağımlılıklarını Kur (FFmpeg)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Gerekli Python Kütüphanelerini Yükle
      run: |
        pip install google-auth-oauthlib google-api-python-client gTTS moviepy requests pytrends

    - name: Python Kodunu Çalıştır
      env:
        TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
      run: python main.py
