name: Free 3D Video Bot

on:
  schedule:
    - cron: '0 18 * * *' # Her gün TSİ 21:00'de (Küresel Prime Time) otomatik çalışır
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Çek
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: FFmpeg Hazır Kurulum (1 Saniye)
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install gradio_client moviepy google-api-python-client google-auth-oauthlib google-auth-httplib2 requests yt-dlp

      - name: Botu Çalıştır
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: python main.py
