name: YouTube Otomatik Yukleme

on:
  schedule:
    # Her gün Türkiye saatiyle 09:00'da otomatik çalışır (UTC 06:00)
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Yükle
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 gtts moviepy requests Pillow

      - name: Botu Çalıştır
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python main.py
