name: YouTube Shorts Creator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Sistem Kütüphanelerini Kur (FFmpeg ve ImageMagick)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick
          sudo sed -i 's/domain="coder" rights="none" pattern="PDF"/domain="coder" rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Shorts Oluştur ve Yükle
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: python main.py
